//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xTrader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XTRADER_DIALOG              102
#define IDD_LOGIN                       104
#define IDD_DLG_NOTICE                  105
#define IDS_TRADE_STAT                  106
#define IDS_MD_STAT                     107
#define IDS_RESPINFO                    108
#define IDS_SFETIME                     109
#define IDS_DCETIME                     110
#define IDS_ZCETIME                     111
#define IDS_CFXTIME                     112
#define IDS_INETIME                     113
#define IDS_DISCONTIPS                  114
#define IDR_CONFBAK                     115
#define IDR_MAINFRAME                   116
#define IDR_MAINMENU                    130
#define IDS_TITLE                       131
#define IDD_DLG_NETSET                  132
#define IDS_STREMPTY                    133
#define IDD_DLG_MODPASS                 134
#define IDS_CFMPASSERR                  135
#define IDS_STRTIPS                     136
#define IDD_BFTRANS                     137
#define IDS_USERPASSERR                 138
#define IDS_ACCPASSERR                  139
#define IDR_LSTRMENU1                   140
#define IDS_MODPASSOK                   141
#define IDD_DLG_GENMRFEE                142
#define IDD_DLG_HISETM                  143
#define IDS_MD_TIPS                     144
#define IDS_TRADE_TIPS                  145
#define IDS_SHFE                        146
#define IDS_DCE                         147
#define IDS_CZCE                        148
#define IDS_CFFEX                       149
#define IDS_CINE                        150
#define IDS_BFTRANS_OK                  151
#define IDD_DLG_BFDETAILS               152
#define IDS_QRYBKERR                    153
#define IDD_DLG_RECENT                  154
#define IDD_PARKORD_DLG                 155
#define IDD_DLG_BKRNT                   156
#define IDD_DLG_ORDEX                   157
#define IDD_UNLOCK                      165
#define IDD_SILOGIN                     166
#define IDC_COMB_SER                    1001
#define IDC_NETSET                      1002
#define IDC_ISPLIST                     1003
#define IDC_USERNAME                    1004
#define IDC_PASSWORD                    1005
#define IDC_SAVE                        1006
#define IDC_PROGRESS                    1007
#define IDC_LOGINFO                     1008
#define IDC_MDPAN                       1009
#define IDC_S1P                         1010
#define IDC_S1V                         1011
#define IDC_LASTP                       1012
#define IDC_LASTV                       1013
#define IDC_B1P                         1014
#define IDC_B1V                         1015
#define IDC_STOTAL                      1016
#define IDC_VTOTAL                      1017
#define IDC_SOPEN                       1018
#define IDC_VOPEN                       1019
#define IDC_SUPDOWN                     1020
#define IDC_DUPDOWN                     1021
#define IDC_SHIGHEST                    1022
#define IDC_DHIGHEST                    1023
#define IDC_SOPT                        1024
#define IDC_DOPT                        1025
#define IDC_SLOWEST                     1026
#define IDC_DLOWEST                     1027
#define IDC_SSMP                        1028
#define IDC_DSMP                        1029
#define IDC_UPTIME                      1030
#define IDC_SS1                         1031
#define IDC_SLAST                       1032
#define IDC_SB1                         1033
#define IDC_INST                        1034
#define ID_EXIT                         1035
#define ID_USERINFO                     1036
#define ID_TRANSBF                      1037
#define ID_HELP_ABOUT                   1038
#define ID_TIPS                         1039
#define IDC_CHKTRANS                    1040
#define ID_VIEW_TOP                     1041
#define IDC_COMB_BS                     1042
#define IDC_COMB_OC                     1043
#define IDC_BTORDER                     1044
#define IDC_EDVOL                       1045
#define IDC_EDPRICE                     1046
#define IDC_SPINVOL                     1047
#define IDC_SPINPRICE                   1048
#define IDC_CHK_NEWP                    1049
#define IDC_LST_ODINF                   1050
#define IDC_LST_ONROAD                  1051
#define IDC_LST_TRADE                   1052
#define IDC_LST_INVPOS                  1053
#define IDC_LST_ALLINST                 1054
#define IDC_TABPAGE                     1055
#define IDC_GRPACC                      1056
#define IDC_CPYK                        1057
#define IDC_HPYK                        1058
#define IDC_TDFEE                       1059
#define IDC_BTQRYACC                    1060
#define IDSHELL_RESTORE                 1061
#define IDSHELL_ABOUT                   1063
#define IDSHELL_EXIT                    1064
#define IDC_NTMSG                       1065
#define IDR_TIPS                        1066
#define IDC_CBNETTYPE                   1067
#define IDC_CHK_SOCK                    1068
#define IDC_SOCKSERV                    1069
#define IDC_SOCK_PORT                   1070
#define IDC_SK_USER                     1071
#define IDC_SKPWD                       1072
#define ID_LOCAL_SEND                   1073
#define IDC_LST_MD                      1074
#define ID_MODPASS                      1075
#define IDC_ORIPASS                     1076
#define IDC_NEWPASS                     1077
#define IDC_NEWPASSCFM                  1078
#define IDC_TRADEPASS                   1079
#define IDC_ACCPASS                     1080
#define IDC_CBBKLST                     1081
#define IDC_ACCPASSWD                   1082
#define IDC_BKPASSWD                    1083
#define IDC_TRANSAMT                    1084
#define IDC_CBEXHTYPE                   1086
#define IDC_BTNQRYBK                    1087
#define IDC_BTNQRYFT                    1088
#define IDC_BTNFT2BK                    1089
#define IDC_BTNBK2FT                    1090
#define IDC_QRYDETAIL                   1091
#define IDC_BT_GENMR                    1092
#define IDC_BT_GENFEE                   1093
#define IDC_GENSTAT                     1094
#define IDC_DTPICK                      1095
#define IDC_BT_QRYDAY                   1096
#define IDC_BT_QRYMONTH                 1097
#define IDC_BT_SAVEFILE                 1098
#define IDC_EDIT_HISOD                  1099
#define IDC_LST_BFDETAILS               1100
#define IDC_BTCLOSE                     1101
#define IDC_STAVOL                      1102
#define IDC_BKR_LIST                    1103
#define IDC_LBRECENT                    1104
#define IDC_CHK_RECENT                  1105
#define IDC_EXTRA                       1106
#define IDS_SHELL_RUN                   1107
#define IDS_SHELL_STOP                  1108
#define IDC_LST_PARKORD                 1109
#define IDS_CFMQUIT                     1110
#define IDC_PARK_LOCAL                  1111
#define IDC_PARK_TMORD                  1112
#define IDC_PARK_REMT                   1113
#define IDS_XTHELP                      1114
#define IDC_CONDORD                     1115
#define IDS_GERR                        1116
#define IDC_CBBASEPX                    1117
#define IDS_ACC_DETAILS                 1118
#define IDC_CBCONDS                     1119
#define IDS_TDNT_TITLE                  1120
#define IDC_STOPPX                      1121
#define IDS_BKRNT_TITLE                 1122
#define IDC_SPSTOPPX                    1123
#define IDS_CFMMC_TITLE                 1124
#define IDC_BT_GENORDFR                 1125
#define IDS_BKACC_LEFT                  1126
#define ID_RELOGIN                      1127
#define IDS_BFTRANS_TITLE               1128
#define IDC_DYMPWD                      1129
#define IDS_CONN_ERR                    1130
#define IDC_BTLBDEL                     1131
#define IDS_ACC_FBINFO                  1132
#define IDC_HTMLVIEW                    1133
#define IDS_CFG_FILE                    1134
#define IDC_PARKORDSTAT                 1135
#define IDS_HK_CFG                      1136
#define IDC_CONDLOCAL                   1137
#define IDS_BKRS_DIR                    1138
#define IDC_LOGIN                       1139
#define IDC_LOGOUT                      1140
#define IDS_NOUIDPWD                    1141
#define IDS_LOADFEE_ERR                 1142
#define IDS_LOADMGR_ERR                 1143
#define IDS_MY_TIPS                     1144
#define IDS_GETTMERR                    1145
#define IDS_SYNCTMERR                   1146
#define IDS_SYNCTMOK                    1147
#define IDS_F2BKMSG                     1148
#define IDS_BK2FMSG                     1149
#define IDC_TOUCH                       1150
#define IDS_TMLESSNOW                   1151
#define IDC_TOUCHPROF                   1152
#define IDS_CFGERR                      1153
#define IDC_RDPKANY                     1154
#define IDC_TMEDIT                      1155
#define IDC_RD_DSJ                      1156
#define IDC_RDLMTPX                     1157
#define IDC_BTEXPAND                    1158
#define IDC_CBPKINST                    1159
#define IDC_CBBSPK                      1160
#define IDC_CBOCPK                      1161
#define IDC_EDPXPK                      1162
#define IDC_EDVOLPK                     1163
#define IDC_SPPXPK                      1164
#define IDC_SPVOLPK                     1165
#define IDC_CHK_MAIN                    1166
#define IDS_CFXBT_TITLE                 1167
#define IDC_CBINST_EX                   1168
#define IDC_EDPX_EX                     1169
#define IDC_EDVOL_EX                    1170
#define IDS_STRBID1                     1171
#define IDS_STRASK1                     1172
#define IDS_CNYSIGN                     1173
#define IDC_CHKMAIN_EX                  1174
#define IDC_GRPLMT                      1175
#define IDC_GRPANY                      1176
#define IDC_BTBUYOPEN                   1177
#define IDC_BTBUYCLOSE                  1178
#define IDC_BTSELLOPEN                  1179
#define IDC_BTSELLCLOSE                 1180
#define IDC_BTCOVOPEN                   1181
#define IDC_BTCOVCLOSE                  1182
#define IDC_BTEXEC                      1183
#define IDC_BTABANDON                   1184
#define IDC_BTCOMB                      1185
#define IDC_BTUNCOMB                    1186
#define IDC_RDNORMAL                    1187
#define IDC_RDFOK                       1188
#define IDC_RDFAK                       1189
#define IDC_CHKMINVOL                   1190
#define IDC_EDITMINVOL                  1191
#define IDC_RDANYNORMAL                 1192
#define IDC_RDBESTANY                   1193
#define IDC_RDL2BEST                    1194
#define IDC_RDANYLMT                    1195
#define IDC_RDBESTLMT                   1196
#define IDC_RDL2LMT                     1197
#define IDC_MAINTRANS                   1198
#define IDC_GRPTBTYPE                   1199
#define IDC_RDSPECU                     1200
#define IDC_RDARBIT                     1201
#define IDC_RDHEDGE                     1202
#define IDC_RDMARKETM                   1203
#define IDC_BTQUITEX                    1204
#define IDC_SPPXEX                      1205
#define IDC_SPVOLEX                     1206
#define IDC_SPMINVOLEX                  1207
#define IDC_CHKORDTO                    1208
#define IDC_EDORDTOSEC                  1209
#define IDS_MBLOG_URL                   1210
#define IDS_MINIDUMP                    1211
#define IDS_OPTIONS_CFG                 1212
#define IDS_XTMDUMP_FAIL                1213
#define IDC_NOTLOCORD                   1214
#define IDS_UNLPWDERR                   1215
#define IDC_CLRB4FINISH                 1216
#define IDC_EDNSEC                      1217
#define IDC_NPXTICK                     1218
#define IDC_AUTOCLOSE                   1219
#define IDC_SPPXTICK                    1220
#define IDC_UNLOCKPWD                   1221
#define ID_UNLOCKOK                     1222
#define IDC_ULQUIT                      1223
#define IDC_STAULMSG                    1224
#define IDC_PRGSILOGIN                  1225
#define IDC_SLISTAMSG                   1226
#define IDC_CHKMXINST                   1227
#define IDS_ORDCONFIRM                  1228
#define IDC_CHKVOLMX                    1229
#define IDC_CHKTDBAR                    1230
#define IDC_CHKORDCONFIRM               1231
#define IDC_STA_MSGTXT                  1232
#define IDS_DIFORD_TITLE                1233
#define IDC_EDIT_INP1                   1250
#define IDC_CHKIDLE                     1254
#define ID_TESTSPEED                    1286
#define IDC_STAHKMSG                    1288
#define IDC_STAMISCMSG                  1289
#define IDC_CHKNOAGAIN                  1290
#define IDS_SVRURLERR                   1291
#define IDC_STACHKMSG                   1292
#define ID_TOOL_PARKED                  1999
#define ID_CANCEL_ORD                   2000
#define ID_REVORD                       2001
#define ID_CANCEL_ALL                   2002
#define ID_MOD_DSJ                      2003
#define ID_CFMMC                        2004
#define ID_GENMDFEE                     2005
#define ID_HISETTINF                    2006
#define ID_HKEY                         2007
#define ID_CSV_EXPORT                   2008
#define ID_REV_ANYPX                    2009
#define ID_GLOKEY                       2010
#define ID_BKRNOTICE                    2011
#define ID_TDNOTICE                     2012
#define ID_LOCAL_REMV                   2013
#define ID_PK_CANCEL                    2014
#define ID_PK_DELCANCEL                 2015
#define ID_PK_REMV                      2016
#define ID_COND_ACT                     2017
#define ID_MINI_MENU                    2018
#define ID_MINI_TASK                    2019
#define ID_ORDER_EXT                    2020
#define ID_COMMCFG                      2021
#define ID_VIEWLOG                      2022
#define ID_LOCK                         2023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         2024
#define _APS_NEXT_CONTROL_VALUE         1293
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
